Repository 202306-NEA-DZ-FEW/HopeHub, pull requests merged in 2023-11, with the labels that each got.

#57 feat(updatetherapist page): create Update therapist page
  public/assets/cards/main.svg
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/pages/Profile/index.jsx
  src/pages/therapist/updateTherapist.jsx
Labels: enhancement

#60 feat(bookin appointment): save user booking infos, add appointments to calendar
  package-lock.json
  package.json
  public/assets/calendarIcon.svg
  src/components/HomePage/TherapistsInfoSection.jsx
  src/components/Navbar/Navbar.jsx
  src/components/booking/1TypeOfCounseling.jsx
  src/components/booking/2RelationshipStatus.jsx
  src/components/booking/3Therapy.jsx
  src/components/booking/5Issues.jsx
  src/components/booking/6Description.jsx
  src/components/booking/7Submission.jsx
  src/components/booking/PickaDate.jsx
  src/components/booking/__test__/PickaDate.test.js
  src/components/booking/__test__/__snapshots__/1TypeOfCounseling.test.js.snap
  src/components/booking/__test__/__snapshots__/2RelationshipStatus.test.js.snap
  src/components/booking/__test__/__snapshots__/3Therapy.test.js.snap
  src/components/booking/__test__/__snapshots__/PickaDate.test.js.snap
  src/context/state.js
  src/data/hours.js
  src/pages/Profile/index.jsx
  src/pages/booking/index.jsx
  src/pages/calendar/index.jsx
  src/styles/PickaDate.module.css
Labels: enhancement

#55 47 update user profile
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/context/state.js
  src/pages/Auth/index.jsx
  src/pages/Profile/index.jsx
Labels: enhancement

#78 Feature/blogs page
  next.config.js
  package-lock.json
  package.json
  public/assets/blog1.jpg
  public/assets/blog2.jpg
  public/assets/blog3.jpg
  public/assets/blog4.jpg
  public/assets/blog5.jpg
  public/assets/blog6.jpg
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/BlogsCard/BlogsCard.jsx
  src/components/BlogsCard/__test__/BlogsCard.test.js
  src/components/BlogsCard/__test__/__snapshots__/BlogsCard.test.js.snap
  src/components/BookingButton/BookingButton.jsx
  src/components/BookingButton/__test__/BookingButton.test.js
  src/components/BookingButton/__test__/__snapshots__/BookingButton.test.js.snap
  src/components/HomePage/Banner.jsx
  src/components/HomePage/BlogsCarousel.jsx
  src/components/HomePage/TherapistsInfoSection.jsx
  src/components/HomePage/__test__/BlogsCarousel.test.txt
  src/components/HomePage/__test__/__snapshots__/Banner.test.js.snap
  src/components/HomePage/__test__/__snapshots__/BlogsCarousel.test.js.snap
  src/components/HomePage/__test__/__snapshots__/BlogsCarousel.test.js.txt
  src/components/HomePage/__test__/__snapshots__/TherapistsInfoSection.test.js.snap
  src/data/blogsData.js
  src/layout/Layout.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/blogs/index.jsx
  src/styles/globals.css
Labels: enhancement

#79 refactor(blogpage): add darkmode
  next.config.js
  src/components/BlogsCard/BlogsCard.jsx
  src/components/BlogsCard/__test__/BlogsCard.test.js
  src/components/BlogsCard/__test__/__snapshots__/BlogsCard.test.js.snap
  src/components/BookingButton/BookingButton.jsx
  src/components/BookingButton/__test__/BookingButton.test.js
  src/components/BookingButton/__test__/__snapshots__/BookingButton.test.js.snap
  src/components/HomePage/__test__/__snapshots__/Banner.test.js.snap
  src/components/HomePage/__test__/__snapshots__/TherapistsInfoSection.test.js.snap
  src/layout/Layout.jsx
  src/pages/_document.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/blogs/index.jsx
  src/styles/globals.css
Labels: enhancement

#81 Fixes/navbar
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/Navbar/Navbar.jsx
  src/components/PaymentForm/PaymentForm.jsx
  src/components/UserAuth/login.jsx
  src/context/state.js
  src/layout/Layout.jsx
  src/pages/Auth/index.jsx
  src/pages/Payment/index.jsx
  src/pages/Profile/index.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/blogs/index.jsx
  src/styles/globals.css
Labels: enhancement

#85 fix(home page): fix learn more button linking issue
  src/components/HomePage/ConnectionSection.jsx
  src/components/HomePage/PurchasingSection.jsx
  src/components/HomePage/__test__/__snapshots__/ConnectionSection.test.js.snap
  src/components/HomePage/__test__/__snapshots__/PurchasingSection.test.js.snap
  src/pages/about/index.jsx
  src/pages/index.jsx
  src/pages/requirement/index.jsx
Labels: enhancement

#97 feat(all pages): add toast notification for alerts, warnings and succ…
  package-lock.json
  package.json
  src/components/ContactForm/ContactForm.jsx
  src/components/ContactForm/__test__/__snapshots__/ContactForm.test.js.snap
  src/components/Footer/Footer.jsx
  src/components/UserAuth/login.jsx
  src/components/UserAuth/signup.jsx
  src/components/booking/1TypeOfCounseling.jsx
  src/components/booking/2RelationshipStatus.jsx
  src/components/booking/3Therapy.jsx
  src/components/booking/4CounseQualities.jsx
  src/components/booking/5Issues.jsx
  src/components/booking/6Description.jsx
  src/components/booking/PickaDate.jsx
  src/pages/Profile/index.jsx
  src/pages/_app.jsx
  src/pages/contact/index.jsx
  src/pages/therapist/index.jsx
  src/pages/therapist/updateTherapist.jsx
Labels: enhancement

#100 Fixes/auth
  package-lock.json
  package.json
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/HomePage/Banner.jsx
  src/components/HomePage/PurchasingSection.jsx
  src/components/HomePage/TherapistsInfoSection.jsx
  src/components/HomePage/__test__/__snapshots__/Banner.test.js.snap
  src/components/HomePage/__test__/__snapshots__/TherapistsInfoSection.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/ProtectedRoute/ProtectedRoute.jsx
  src/components/ProtectedRoute/__test__/ProtectedRoute.test.js
  src/components/ProtectedRoute/__test__/__snapshots__/ProtectedRoute.test.js.snap
  src/components/UserAuth/login.jsx
  src/context/state.js
  src/pages/Auth/index.jsx
  src/pages/Profile/index.jsx
  src/pages/admin/index.jsx
  src/pages/blogs/index.jsx
  src/pages/booking/index.jsx
  src/pages/calendar/index.jsx
  src/pages/therapist/index.jsx
Labels: enhancement

#113 README.md
  README.md
Labels: documentation

#117 refactor(animation): add simple animation to the website
  babel.config.js
  package-lock.json
  package.json
  public/assets/Group181.png
  public/assets/Group182.png
  src/components/About/FoundingTab.jsx
  src/components/About/TeamTab.jsx
  src/components/About/__test__/TeamTab.test.js
  src/components/About/__test__/__snapshots__/FoundingTab.test.js.snap
  src/components/About/__test__/__snapshots__/TeamTab.test.js.snap
  src/components/AdminDashboard/Blogs.jsx
  src/components/AdminDashboard/BlogsEdit.jsx
  src/components/AdminDashboard/BlogsEditCopy.jsx
  src/components/AdminDashboard/__test__/BlogsEdit.test.js
  src/components/AdminDashboard/__test__/__snapshots__/BlogsEdit.test.js.snap
  src/components/Checkbox.jsx
  src/components/ContactForm/ContactForm.jsx
  src/components/HomePage/Banner.jsx
  src/components/HomePage/BlogsCarousel.jsx
  src/components/HomePage/ConnectionSection.jsx
  src/components/HomePage/PurchasingSection.jsx
  src/components/HomePage/__test__/__snapshots__/Banner.test.js.snap
  src/components/HomePage/__test__/__snapshots__/ConnectionSection.test.js.snap
  src/components/HomePage/__test__/__snapshots__/PurchasingSection.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/__test__/__snapshots__/Navbar.test.js.snap
  src/components/ProtectedRoute/ProtectedRoute.jsx
  src/components/StripePayment/CheckoutURL.jsx
  src/components/User/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/User/__test__/__snapshots__/updateTherapist.test.js.snap
  src/components/booking/1TypeOfCounseling.jsx
  src/components/booking/2RelationshipStatus.jsx
  src/components/booking/3Therapy.jsx
  src/components/booking/4CounseQualities.jsx
  src/components/booking/5Issues.jsx
  src/components/booking/6Description.jsx
  src/components/booking/7Submission.jsx
  src/components/booking/8Confirmation.jsx
  src/data/blogsData.js
  src/layout/Layout.jsx
  src/pages/_document.jsx
  src/pages/about/index.jsx
  src/pages/admin/index.jsx
  src/pages/blogs/index.jsx
  src/pages/careers/index.jsx
  src/pages/contact/index.jsx
  src/pages/index.jsx
  src/pages/requirement/index.jsx
  src/styles/globals.css
  src/util/constants.js
  tailwind.config.js
Labels: enhancement

#120 fix thank you page
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/pages/thanks/index.jsx
Labels: enhancement

#122 Newsletter Content
  package-lock.json
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
Labels: enhancement

#94 feat(contact page): adding the send email functionality
  public/assets/AvatarPlaceHolder.svg
  src/components/AdminDashboard/Patients.jsx
  src/components/AdminDashboard/ReceivedEmails.jsx
  src/components/AdminDashboard/Therapists.jsx
  src/components/AdminDashboard/__test__/ReceivedEmails.test.js
  src/components/AdminDashboard/__test__/__snapshots__/ReceivedEmails.test.js.snap
  src/components/ContactForm/ContactForm.jsx
  src/components/ContactForm/__test__/__snapshots__/ContactForm.test.js.snap
  src/components/HomePage/ConnectionSection.jsx
  src/components/HomePage/__test__/__snapshots__/ConnectionSection.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/components/User/__test__/__snapshots__/updateTherapist.test.js.snap
  src/pages/_document.jsx
  src/pages/admin/index.jsx
  src/pages/blogs/index.jsx
  src/pages/contact/index.jsx
Labels: enhancement

#133 feat(career page): create individual job page
  public/assets/CareersOffice.jpg
  public/assets/CareersPage.jpg
  public/assets/RequirementPage.jpg
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/AdminDashboard/BlogsEditCopy.jsx
  src/components/AdminDashboard/Jobs.jsx
  src/components/AdminDashboard/JobsEdit.jsx
  src/components/AdminDashboard/ReceivedEmails.jsx
  src/components/AdminDashboard/__test__/Jobs.test.js
  src/components/AdminDashboard/__test__/JobsEdit.test.js
  src/components/AdminDashboard/__test__/__snapshots__/Jobs.test.js.snap
  src/components/AdminDashboard/__test__/__snapshots__/JobsEdit.test.js.snap
  src/components/AdminDashboard/__test__/__snapshots__/ReceivedEmails.test.js.snap
  src/components/Footer/Footer.jsx
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/Input/Input.jsx
  src/components/Input/__test__/__snapshots__/Input.test.js.snap
  src/components/JobCard/JobCard.jsx
  src/components/JobCard/__test__/__snapshots__/JobCard.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/components/User/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/User/__test__/__snapshots__/updateTherapist.test.js.snap
  src/context/state.js
  src/pages/admin/index.jsx
  src/pages/careers/[id].jsx
  src/pages/careers/index.jsx
  src/pages/requirement/index.jsx
  src/pages/therapist/index.jsx
  src/styles/BlogContent.module.css
Labels: enhancement

#134 Features/matching
  src/components/User/UserProfile.jsx
  src/components/UserAuth/login.jsx
  src/components/UserAuth/signup.jsx
  src/components/booking/7Submission.jsx
  src/components/calendarEvents/EventModal.jsx
  src/pages/booking/index.jsx
  src/pages/calendar/index.jsx
Labels: enhancement

#137 136 therapist profile
  public/assets/LogoIcon.svg
  src/components/About/TeamTab.jsx
  src/components/About/__test__/__snapshots__/TeamTab.test.js.snap
  src/components/BookingButton/BookingButton.jsx
  src/components/BookingButton/__test__/__snapshots__/BookingButton.test.js.snap
  src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
  src/components/HomePage/TherapistsInfoSection.jsx
  src/components/HomePage/__test__/__snapshots__/Banner.test.js.snap
  src/components/HomePage/__test__/__snapshots__/TherapistsInfoSection.test.js.snap
  src/components/Loader/Loader.jsx
  src/components/Navbar/Navbar.jsx
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/components/NewsletterSignUp/__test__/__snapshots__/NewsletterSignUp.test.js.snap
  src/components/StripePayment/TotalTickets.jsx
  src/components/StripePayment/__test__/__snapshots__/TotalTickets.test.js.snap
  src/components/User/UserProfile.jsx
  src/components/User/__test__/__snapshots__/UserProfile.test.js.snap
  src/components/User/__test__/__snapshots__/updateTherapist.test.js.snap
  src/components/User/__test__/updateTherapist.test.js
  src/components/User/updateTherapist.jsx
  src/components/booking/7Submission.jsx
  src/components/booking/8Confirmation.jsx
  src/components/booking/__test__/8Confirmation.test.js
  src/components/booking/__test__/__snapshots__/7Submission.test.js.snap
  src/components/booking/__test__/__snapshots__/8Confirmation.test.js.snap
  src/pages/Auth/index.jsx
  src/pages/Payment/index.jsx
  src/pages/Tickets/index.jsx
  src/pages/_document.jsx
  src/pages/booking/index.jsx
  src/pages/calendar/index.jsx
  src/pages/call/index.jsx
  src/pages/index.jsx
  src/styles/Calendar.module.css
Labels: Fixes

#142 Features/blogs translation
  public/locales/ar/common.json
  public/locales/en/common.json
  public/locales/fr/common.json
  src/components/BlogsCard/BlogsCard.jsx
  src/components/Booking/1TypeOfCounseling.jsx
  src/components/Booking/2RelationshipStatus.jsx
  src/components/Booking/3Therapy.jsx
  src/components/Booking/4CounseQualities.jsx
  src/components/Booking/5Issues.jsx
  src/components/Booking/6Description.jsx
  src/components/Booking/7Submission.jsx
  src/components/Booking/8Confirmation.jsx
  src/components/Booking/PickaDate.jsx
  src/components/Booking/__test__/__snapshots__/1TypeOfCounseling.test.js.snap
  src/components/Booking/__test__/__snapshots__/2RelationshipStatus.test.js.snap
  src/components/Booking/__test__/__snapshots__/3Therapy.test.js.snap
  src/components/Booking/__test__/__snapshots__/4CounseQualities.test.js.snap
  src/components/Booking/__test__/__snapshots__/5Issues.test.js.snap
  src/components/Booking/__test__/__snapshots__/7Submission.test.js.snap
  src/components/Booking/__test__/__snapshots__/8Confirmation.test.js.snap
  src/components/Booking/__test__/__snapshots__/PickaDate.test.js.snap
  src/components/HomePage/BlogsCarousel.jsx
  src/components/HomePage/PurchasingSection.jsx
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/components/StripePayment/TotalTickets.jsx
  src/components/UserAuth/Signup.jsx
  src/components/UserAuth/__test__/__snapshots__/signup.test.js.snap
  src/components/VideoCall/Videocall.jsx
  src/components/VideoCall/index_.jsx
  src/components/VideoCall/jitsi.jsx
  src/pages/blogs/[blogId].jsx
  src/pages/blogs/index.jsx
  src/pages/booking/index.jsx
  src/pages/calendar/index.jsx
  src/pages/tickets/index.jsx
Labels: Fixes

#143 141 additional fixes
  src/components/Booking/4CounseQualities.jsx
  src/components/Booking/5Issues.jsx
  src/components/Booking/7Submission.jsx
  src/components/Booking/8Confirmation.jsx
  src/components/Booking/Checkbox.jsx
  src/components/Booking/__test__/Checkbox.test.js
  src/components/Booking/__test__/__snapshots__/4CounseQualities.test.js.snap
  src/components/Booking/__test__/__snapshots__/5Issues.test.js.snap
  src/components/Booking/__test__/__snapshots__/8Confirmation.test.js.snap
  src/components/Booking/__test__/__snapshots__/Checkbox.test.js.snap
  src/components/Loader/__test__/Loader.test.js
  src/components/Loader/__test__/__snapshots__/Loader.test.js.snap
  src/components/Navbar/Navbar.jsx
  src/components/User/UpdateTherapist.jsx
  src/components/User/UserProfile.jsx
  src/components/User/__test__/UserProfile.test.js
  src/components/User/__test__/__snapshots__/UserProfile.test.js.snap
  src/pages/_document.jsx
Labels: Fixes

#147 fix(hopehb): fixes in padding
  src/components/Navbar/Navbar.jsx
  src/components/NewsletterSignUp/NewsletterSignUp.jsx
  src/components/UserAuth/Login.jsx
  src/components/UserAuth/Signup.jsx
  src/components/UserAuth/__test__/__snapshots__/login.test.js.snap
  src/components/UserAuth/__test__/__snapshots__/signup.test.js.snap
  src/pages/Auth/index.jsx
  src/pages/booking/index.jsx
  src/pages/thanks/index.jsx
  src/pages/tickets/index.jsx
Labels: Fixes
